// 更新后的 mockWebinars 数据
// 包含不同类型（大型/小型）和场景（TikTok/网红等）的示例

export const updatedMockWebinars = [
  // 大型 Webinar - 新品发布会
  {
    id: 1,
    title: "Smart Home Products Showcase 2026",
    description: "Explore the latest smart home innovations from top Chinese manufacturers. This webinar features live product demonstrations, real-time Q&A sessions, and exclusive pricing for international buyers.",
    type: "large",
    scenario: "product_launch",
    visibility: "public",
    status: "live",
    scheduled_at: new Date().toISOString(),
    duration: 90,
    category: "smart-home",
    language: "en",
    agora_channel_name: "webinar_smart_home_001",
    cover_image: "/covers/smarthome-showcase.png",
    max_participants: 50,
    actual_participants: 42,
    host_type: "factory",
    created_by: "admin",
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  
  // 大型 Webinar - 工厂开放日
  {
    id: 2,
    title: "Consumer Electronics Q1 Sourcing Fair",
    description: "Connect with verified electronics manufacturers for Q1 2026 procurement. Categories include mobile accessories, audio equipment, and wearable devices.",
    type: "large",
    scenario: "factory_tour",
    visibility: "public",
    status: "scheduled",
    scheduled_at: new Date(Date.now() + 3 * 86400000).toISOString(),
    duration: 120,
    category: "electronics",
    language: "en",
    agora_channel_name: "webinar_electronics_q1",
    cover_image: "/covers/medical-innovation.png",
    max_participants: 100,
    actual_participants: 0,
    host_type: "factory",
    created_by: "admin",
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  
  // 小组会议 - TikTok/Dropshipper 产品对接
  {
    id: 3,
    title: "TikTok Hot Products Sourcing Session",
    description: "Fast-track sourcing for TikTok Shop sellers. Connect with 5 verified factories offering low MOQ (100-500 units), fast sampling (7-14 days), and dropshipping support. Perfect for trending products like beauty tools, phone accessories, and home gadgets.",
    type: "small_group",
    scenario: "tiktok_dropshipper",
    visibility: "private",
    status: "scheduled",
    scheduled_at: new Date(Date.now() + 1 * 86400000).toISOString(),
    duration: 60,
    category: "consumer-goods",
    language: "en",
    agora_channel_name: "webinar_tiktok_001",
    cover_image: "/covers/tiktok-sourcing.png",
    max_participants: 8,
    actual_participants: 0,
    host_type: "buyer",
    created_by: "buyer_tiktok_seller",
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  
  // 小组会议 - 网红达人选品对接
  {
    id: 4,
    title: "Influencer Product Selection - Beauty & Personal Care",
    description: "Exclusive product selection session for verified influencers (50K+ followers). 8 beauty manufacturers will showcase their latest products, offer exclusive pricing, and discuss commission structures. Perfect for live streaming and social commerce.",
    type: "small_group",
    scenario: "influencer_selection",
    visibility: "private",
    status: "live",
    scheduled_at: new Date(Date.now() - 0.5 * 3600000).toISOString(),
    duration: 90,
    category: "beauty",
    language: "zh",
    agora_channel_name: "webinar_influencer_001",
    cover_image: "/covers/influencer-selection.png",
    max_participants: 10,
    actual_participants: 9,
    host_type: "buyer",
    created_by: "influencer_beauty_queen",
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  
  // 1对1会议 - 商务谈判
  {
    id: 5,
    title: "Private Negotiation: Custom Medical Equipment Order",
    description: "Confidential discussion for a $500K custom medical equipment order. Topics include product specifications, quality standards, payment terms, and delivery schedule.",
    type: "one_on_one",
    scenario: "negotiation",
    visibility: "private",
    status: "completed",
    scheduled_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    duration: 45,
    category: "medical",
    language: "en",
    agora_channel_name: "webinar_negotiation_001",
    max_participants: 2,
    actual_participants: 2,
    host_type: "buyer",
    created_by: "buyer_medical_corp",
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  
  // 小组会议 - 小批量采购
  {
    id: 6,
    title: "Small Batch Sourcing: Eco-Friendly Packaging",
    description: "Connect with 3 factories that accept small orders (MOQ 200-500 units) for eco-friendly packaging. Ideal for startups and small businesses testing new products.",
    type: "small_group",
    scenario: "small_batch",
    visibility: "semi_public",
    status: "scheduled",
    scheduled_at: new Date(Date.now() + 2 * 86400000).toISOString(),
    duration: 60,
    category: "packaging",
    language: "en",
    agora_channel_name: "webinar_small_batch_001",
    cover_image: "/covers/sustainable-textiles.png",
    max_participants: 6,
    actual_participants: 0,
    host_type: "buyer",
    created_by: "buyer_startup",
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  
  // 大型 Webinar - 行业峰会
  {
    id: 7,
    title: "Global Sources Hong Kong Show Tour",
    description: "A comprehensive tour of the Global Sources Hong Kong show, featuring top electronics and lifestyle suppliers. Join 100+ buyers and 20+ exhibitors for this virtual tour.",
    type: "large",
    scenario: "industry_summit",
    visibility: "public",
    status: "completed",
    scheduled_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    duration: 180,
    category: "electronics",
    language: "en",
    agora_channel_name: "webinar_hk_show_tour",
    cover_image: "/global-sources-tour.png",
    max_participants: 200,
    actual_participants: 156,
    host_type: "factory",
    created_by: "admin",
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  
  // 中型 Webinar - 常规商务会议
  {
    id: 8,
    title: "LED Lighting Solutions 2026",
    description: "Annual LED lighting sourcing event featuring the newest energy-efficient lighting technologies, smart lighting systems, and commercial lighting solutions.",
    type: "medium",
    scenario: "general",
    visibility: "semi_public",
    status: "scheduled",
    scheduled_at: new Date(Date.now() + 8 * 86400000).toISOString(),
    duration: 90,
    category: "electronics",
    language: "zh",
    agora_channel_name: "webinar_led_2026",
    cover_image: "/led-lighting-solutions.png",
    max_participants: 25,
    actual_participants: 0,
    host_type: "factory",
    created_by: "factory_led_corp",
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  
  // 小组会议 - TikTok 产品对接（已完成）
  {
    id: 9,
    title: "TikTok Trending: Phone Accessories Sourcing",
    description: "Successful sourcing session for TikTok trending phone accessories. Connected 1 TikTok seller with 4 factories. Result: 2 sample orders placed, estimated order value $15K.",
    type: "small_group",
    scenario: "tiktok_dropshipper",
    visibility: "private",
    status: "completed",
    scheduled_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    duration: 45,
    category: "electronics",
    language: "en",
    agora_channel_name: "webinar_tiktok_phone",
    max_participants: 6,
    actual_participants: 5,
    host_type: "buyer",
    created_by: "buyer_tiktok_phone",
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  
  // 小组会议 - 网红选品（已完成）
  {
    id: 10,
    title: "Influencer Selection: Home Decor Products",
    description: "Successful product selection for home decor influencer (200K followers). Selected 5 products from 3 factories. Estimated monthly sales: $50K, commission: 15%.",
    type: "small_group",
    scenario: "influencer_selection",
    visibility: "private",
    status: "completed",
    scheduled_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    duration: 75,
    category: "home-decor",
    language: "zh",
    agora_channel_name: "webinar_influencer_home",
    max_participants: 8,
    actual_participants: 7,
    host_type: "buyer",
    created_by: "influencer_home_decor",
    created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
];
