// 新增的 Webinar 数据（TikTok/网红场景）
export const newWebinars = `
  // 小组会议 - TikTok/Dropshipper 产品对接
  {
    id: 6,
    title: "TikTok Hot Products Sourcing Session",
    description: "Fast-track sourcing for TikTok Shop sellers. Connect with 5 verified factories offering low MOQ (100-500 units), fast sampling (7-14 days), and dropshipping support. Perfect for trending products like beauty tools, phone accessories, and home gadgets.",
    type: "small_group",
    scenario: "tiktok_dropshipper",
    visibility: "private",
    status: "scheduled",
    scheduled_at: new Date(Date.now() + 1 * 86400000).toISOString(),
    duration: 60,
    category: "consumer-goods",
    language: "en",
    agora_channel_name: "webinar_tiktok_001",
    cover_image: "/covers/tiktok-sourcing.png",
    max_participants: 8,
    actual_participants: 0,
    host_type: "buyer",
    created_by: "buyer_tiktok_seller",
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  // 小组会议 - 网红达人选品对接
  {
    id: 7,
    title: "Influencer Product Selection - Beauty & Personal Care",
    description: "Exclusive product selection session for verified influencers (50K+ followers). 8 beauty manufacturers will showcase their latest products, offer exclusive pricing, and discuss commission structures. Perfect for live streaming and social commerce.",
    type: "small_group",
    scenario: "influencer_selection",
    visibility: "private",
    status: "scheduled",
    scheduled_at: new Date(Date.now() + 2 * 86400000).toISOString(),
    duration: 90,
    category: "beauty",
    language: "zh",
    agora_channel_name: "webinar_influencer_001",
    cover_image: "/covers/influencer-selection.png",
    max_participants: 10,
    actual_participants: 0,
    host_type: "buyer",
    created_by: "influencer_beauty_queen",
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
`;
