// Mock factory data for development and testing

export const mockFactories = [
  {
    id: 1,
    name: "Shenzhen Electronics Manufacturing Co., Ltd.",
    location: "Shenzhen, Guangdong",
    province: "Guangdong",
    city: "Shenzhen",
    score: 95,
    category: "Electronics",
    webinars: 12,
    orders: 1234,
    status: "verified",
    employees: "500-1000",
    logo: "https://ui-avatars.com/api/?name=Shenzhen+Electronics&background=2563EB&color=fff&size=200",
    images: [
      "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800",
      "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800",
      "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=800",
    ],
    certifications: [
      { id: 1, name: "ISO 9001", type: "Quality Management" },
      { id: 2, name: "ISO 14001", type: "Environmental" },
      { id: 3, name: "CE", type: "Product Safety" },
    ],
    onTimeRate: 98,
    yearsActive: 15,
    isGoldMember: true,
    isVerified: true,
  },
  {
    id: 2,
    name: "Hangzhou Textile Industry Group",
    location: "Hangzhou, Zhejiang",
    province: "Zhejiang",
    city: "Hangzhou",
    score: 92,
    category: "Textiles",
    webinars: 8,
    orders: 856,
    status: "verified",
    employees: "1000-5000",
    logo: "https://ui-avatars.com/api/?name=Hangzhou+Textile&background=10B981&color=fff&size=200",
    images: [
      "https://images.unsplash.com/photo-1558769132-cb1aea3c8e5e?w=800",
      "https://images.unsplash.com/photo-1562157873-818bc0726f68?w=800",
    ],
    certifications: [
      { id: 4, name: "OEKO-TEX", type: "Textile Safety" },
      { id: 5, name: "GOTS", type: "Organic Textiles" },
    ],
    onTimeRate: 96,
    yearsActive: 22,
    isGoldMember: true,
    isVerified: true,
  },
  {
    id: 3,
    name: "Shanghai Precision Machinery Manufacturing",
    location: "Shanghai, Shanghai",
    province: "Shanghai",
    city: "Shanghai",
    score: 88,
    category: "Machinery",
    webinars: 5,
    orders: 432,
    status: "verified",
    employees: "200-500",
    logo: "https://ui-avatars.com/api/?name=Shanghai+Machinery&background=F59E0B&color=fff&size=200",
    images: [
      "https://images.unsplash.com/photo-1565793298595-6a879b1d9492?w=800",
    ],
    certifications: [
      { id: 6, name: "ISO 9001", type: "Quality Management" },
    ],
    onTimeRate: 94,
    yearsActive: 18,
    isGoldMember: false,
    isVerified: true,
  },
  {
    id: 4,
    name: "Guangzhou Furniture Manufacturing Ltd.",
    location: "Guangzhou, Guangdong",
    province: "Guangdong",
    city: "Guangzhou",
    score: 85,
    category: "Furniture",
    webinars: 3,
    orders: 678,
    status: "verified",
    employees: "100-200",
    logo: "https://ui-avatars.com/api/?name=Guangzhou+Furniture&background=8B5CF6&color=fff&size=200",
    images: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800",
      "https://images.unsplash.com/photo-1567016432779-094069958ea5?w=800",
    ],
    certifications: [
      { id: 7, name: "FSC", type: "Forest Stewardship" },
      { id: 8, name: "CARB", type: "Air Quality" },
    ],
    onTimeRate: 92,
    yearsActive: 12,
    isGoldMember: false,
    isVerified: true,
  },
  {
    id: 5,
    name: "Beijing Auto Parts Supplier Co.",
    location: "Beijing, Beijing",
    province: "Beijing",
    city: "Beijing",
    score: 90,
    category: "Automotive",
    webinars: 7,
    orders: 945,
    status: "verified",
    employees: "500-1000",
    logo: "https://ui-avatars.com/api/?name=Beijing+Auto&background=EF4444&color=fff&size=200",
    images: [
      "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800",
    ],
    certifications: [
      { id: 9, name: "IATF 16949", type: "Automotive Quality" },
      { id: 10, name: "ISO 9001", type: "Quality Management" },
    ],
    onTimeRate: 97,
    yearsActive: 20,
    isGoldMember: true,
    isVerified: true,
  },
  {
    id: 6,
    name: "Ningbo Plastic Products Factory",
    location: "Ningbo, Zhejiang",
    province: "Zhejiang",
    city: "Ningbo",
    score: 82,
    category: "Plastics",
    webinars: 2,
    orders: 523,
    status: "verified",
    employees: "50-100",
    logo: "https://ui-avatars.com/api/?name=Ningbo+Plastic&background=06B6D4&color=fff&size=200",
    images: [],
    certifications: [
      { id: 11, name: "ISO 9001", type: "Quality Management" },
    ],
    onTimeRate: 89,
    yearsActive: 8,
    isGoldMember: false,
    isVerified: true,
  },
  {
    id: 7,
    name: "Dongguan LED Lighting Manufacturing",
    location: "Dongguan, Guangdong",
    province: "Guangdong",
    city: "Dongguan",
    score: 93,
    category: "Electronics",
    webinars: 10,
    orders: 1105,
    status: "verified",
    employees: "200-500",
    logo: "https://ui-avatars.com/api/?name=Dongguan+LED&background=F97316&color=fff&size=200",
    images: [
      "https://images.unsplash.com/photo-1513828583688-c52646db42da?w=800",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
    ],
    certifications: [
      { id: 12, name: "CE", type: "Product Safety" },
      { id: 13, name: "RoHS", type: "Hazardous Substances" },
      { id: 14, name: "UL", type: "Safety Certification" },
    ],
    onTimeRate: 95,
    yearsActive: 11,
    isGoldMember: true,
    isVerified: true,
  },
  {
    id: 8,
    name: "Suzhou Semiconductor Equipment Co.",
    location: "Suzhou, Jiangsu",
    province: "Jiangsu",
    city: "Suzhou",
    score: 91,
    category: "Electronics",
    webinars: 6,
    orders: 789,
    status: "verified",
    employees: "100-200",
    logo: "https://ui-avatars.com/api/?name=Suzhou+Semiconductor&background=6366F1&color=fff&size=200",
    images: [
      "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800",
    ],
    certifications: [
      { id: 15, name: "ISO 9001", type: "Quality Management" },
      { id: 16, name: "SEMI S2", type: "Semiconductor Safety" },
    ],
    onTimeRate: 96,
    yearsActive: 14,
    isGoldMember: false,
    isVerified: true,
  },
  {
    id: 9,
    name: "Chengdu Food Processing Equipment Ltd.",
    location: "Chengdu, Sichuan",
    province: "Sichuan",
    city: "Chengdu",
    score: 78,
    category: "Food & Beverage",
    webinars: 1,
    orders: 234,
    status: "pending",
    employees: "50-100",
    logo: "https://ui-avatars.com/api/?name=Chengdu+Food&background=84CC16&color=fff&size=200",
    images: [],
    certifications: [
      { id: 17, name: "FDA", type: "Food Safety" },
    ],
    onTimeRate: 87,
    yearsActive: 5,
    isGoldMember: false,
    isVerified: false,
  },
  {
    id: 10,
    name: "Wuhan Steel Manufacturing Group",
    location: "Wuhan, Hubei",
    province: "Hubei",
    city: "Wuhan",
    score: 86,
    category: "Metals",
    webinars: 4,
    orders: 612,
    status: "verified",
    employees: "1000-5000",
    logo: "https://ui-avatars.com/api/?name=Wuhan+Steel&background=64748B&color=fff&size=200",
    images: [
      "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800",
    ],
    certifications: [
      { id: 18, name: "ISO 9001", type: "Quality Management" },
      { id: 19, name: "ISO 14001", type: "Environmental" },
    ],
    onTimeRate: 91,
    yearsActive: 25,
    isGoldMember: false,
    isVerified: true,
  },
  {
    id: 11,
    name: "Xiamen Packaging Solutions Inc.",
    location: "Xiamen, Fujian",
    province: "Fujian",
    city: "Xiamen",
    score: 84,
    category: "Packaging",
    webinars: 3,
    orders: 445,
    status: "verified",
    employees: "100-200",
    logo: "https://ui-avatars.com/api/?name=Xiamen+Packaging&background=EC4899&color=fff&size=200",
    images: [
      "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800",
    ],
    certifications: [
      { id: 20, name: "ISO 9001", type: "Quality Management" },
    ],
    onTimeRate: 90,
    yearsActive: 9,
    isGoldMember: false,
    isVerified: true,
  },
  {
    id: 12,
    name: "Qingdao Marine Equipment Manufacturing",
    location: "Qingdao, Shandong",
    province: "Shandong",
    city: "Qingdao",
    score: 89,
    category: "Marine",
    webinars: 5,
    orders: 567,
    status: "verified",
    employees: "200-500",
    logo: "https://ui-avatars.com/api/?name=Qingdao+Marine&background=0EA5E9&color=fff&size=200",
    images: [
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800",
    ],
    certifications: [
      { id: 21, name: "ISO 9001", type: "Quality Management" },
      { id: 22, name: "ABS", type: "Marine Classification" },
    ],
    onTimeRate: 93,
    yearsActive: 17,
    isGoldMember: false,
    isVerified: true,
  },
];
